import React from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import HeroSection from '../components/HeroSection';
import DCollectionSection from '../components/desktop/DCollectionSection';
import DRoadmapSection from '../components/desktop/DRoadmapSection';
import DFaqSection from '../components/desktop/DFaqSection';
import DTeamSection from '../components/desktop/DTeamSection';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className="bg-gray-900">
      <Head>
        <title>Chuel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />
      <HeroSection />

      {/* For Desktop */}
      <div className="hidden md:block">
        <DCollectionSection />
        <DRoadmapSection />
        <DFaqSection />
        <DTeamSection />
      </div>

      {/* For Mobile */}
      <div className="block md:hidden">

      </div>
      <Footer />
    </div>
  );
}
