import React from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import DHeroSection from '../components/desktop/DHeroSection';
import DCollectionSection from '../components/desktop/DCollectionSection';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Chuel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <DHeroSection />
      <DCollectionSection />
    </div>
  );
}
